# This is a basic workflow to help you get started with Actions

name: Learn GitHub Actions

# Controls when the workflow will run
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Docker Image to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Store private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ./id_rsa
          cat ~/.ssh/known_hosts
          ssh pavel@135.181.204.220 -4 -p 9922 -i $(pwd)/id_rsa 'ls -lah /srv'
