# This is a basic workflow to help you get started with Actions

name: Learn GitHub Actions

# Controls when the workflow will run
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Docker Image to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 15
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Store private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ./id_rsa
          node ./deploy.js pavel 135.181.204.220 ./id_rsa
