# This is a basic workflow to help you get started with Actions

name: Learn GitHub Actions

# Controls when the workflow will run
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Docker Image to server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docker container
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: "github-actions@65.21.109.224:9922"
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: false
          command: |
            cd /srv
            echo "test" > test.txt
