# This is a basic workflow to help you get started with Actions

name: Learn GitHub Actions

# Controls when the workflow will run
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Docker Image to server
    runs-on: ubuntu-latest
    steps:
      - name: Store private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ./id_rsa
          node run ./deploy.js pavel 135.181.204.220 ./id_rsa
      - name: Put a test text
        run: ssh hetzner-host -tt 'cd /srv && echo "test" > test.txt'
