# This is a basic workflow to help you get started with Actions

name: Learn GitHub Actions

# Controls when the workflow will run
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Docker Image to server
    runs-on: ubuntu-latest
    steps:
      - name: Store private key
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/id_rsa
          touch ~/.ssh/config
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
          echo "Host hetzner-host" >> ~/.ssh/config
          echo "    HostName 65.21.109.224" >> ~/.ssh/config
          echo "    Port 9922" >> ~/.ssh/config
          echo "    User github-actions" >> ~/.ssh/config
          echo "    IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config

      - name: Put a test text
        run: ssh hetzner-host -t 'cd /srv && echo "test" > test.txt'
