# This is a basic workflow to help you get started with Actions

name: Learn GitHub Actions

# Controls when the workflow will run
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checking out repository
        uses: actions/checkout@v2
      
      - name: Setting up Node environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload build to S3
        uses: koraykoska/s3-upload-github-action@master
        env:
          FILE: ./build/
          S3_ENDPOINT: 'ams3.digitaloceanspaces.com'
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
